name: CI

on:
  push:
    branches: [ main, dev/colab-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps (light)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run notebook fixer
        run: |
          python scripts/fix_notebook_widgets.py site/en
      - name: Run tests
        run: |
          pytest -q -r a

  smoke-generator:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy
      - name: Run smoke generator
        run: |
          python scripts/generate_synthetic_smoke.py

  dry-run-trainer:
    runs-on: ubuntu-latest
    needs: smoke-generator
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy
      - name: Generate smoke CSV (again, ensures file present)
        run: |
          python scripts/generate_synthetic_smoke.py
      - name: Dry-run trainer (constructs trainer, skips heavy training)
        run: |
          python scripts/finetune_gemma_from_csv.py --csv synthetic_wifi_5ghz_outdoor_smoke.csv --dry-run --max-rows 10
