name: CI

on:
  push:
    branches: [ main, dev/colab-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps (light)
        run: |
          python -m pip install --upgrade pip
          # Prefer a lightweight dev requirements file for tests when available
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; else python -m pip install -r requirements.txt; fi
          # Ensure pytest is present for the test step (installed via requirements-dev.txt or explicitly)
          python -m pip install pytest
      - name: CI debug info
        run: |
          echo "--- python & pip versions ---"
          python --version || true
          pip --version || true
          echo "--- pip list (top 50) ---"
          pip list --format=columns | sed -n '1,50p' || true
          echo "--- workspace top-level files ---"
          ls -la || true
          echo "--- find (depth 2) ---"
          find . -maxdepth 2 -type f | sed -n '1,200p' || true
      - name: Run notebook fixer
        run: |
          python scripts/fix_notebook_widgets.py site/en
      - name: Verify pytest available
        run: |
          echo "--- pytest info ---"
          python -m pytest --version || python -c "import pytest; print('pytest', pytest.__version__)" || true
      - name: Run tests
        run: |
          python -m pytest -q -r a

  smoke-generator:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-smoke-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy
      - name: Run smoke generator
        run: |
          python scripts/generate_synthetic_smoke.py

  dry-run-trainer:
    runs-on: ubuntu-latest
    needs: smoke-generator
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-trainer-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy
      - name: Generate smoke CSV (again, ensures file present)
        run: |
          python scripts/generate_synthetic_smoke.py
      - name: Dry-run trainer (constructs trainer, skips heavy training)
        run: |
          python scripts/finetune_gemma_from_csv.py --csv synthetic_wifi_5ghz_outdoor_smoke.csv --dry-run --max-rows 10

  dry-run-lora:
    runs-on: ubuntu-latest
    needs: smoke-generator
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-lora-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy
      - name: Ensure smoke CSV present
        run: |
          python scripts/generate_synthetic_smoke.py
      - name: Dry-run trainer (lora mode)
        run: |
          python scripts/finetune_gemma_from_csv.py --csv synthetic_wifi_5ghz_outdoor_smoke.csv --mode lora --dry-run --max-rows 10
      - name: Evaluate synthetic predictions
        run: |
          python scripts/evaluate_model.py --preds tests/fixtures/preds_synthetic.csv --target-field expected_throughput_mbps --pred-field pred --json-output eval_lora.json
